/**
 * Per-title facts pulled from Wikidata. Generated by \`pnpm metadata\`;
 * do not hand-edit.
 *
 * Streaming availability is deliberately NOT stored: it is regional and it
 * changes constantly. \`watchLinks()\` in ./watch.ts builds aggregator links
 * instead, which stay correct without maintenance.
 *
 * Season entries share their series' article, so they share its IMDb id and
 * creator credit, and carry no release date of their own.
 */
export type TitleMeta = {
  /** IMDb title id, e.g. "tt4154796". */
  imdb?: string;
  /** Films. */
  director?: string[];
  /** Series and specials. */
  creator?: string[];
  /** Minutes; films only. */
  runtime?: number;
  episodes?: number;
  /** Exact release / first-air date, ISO. */
  released?: string;
};

export const METADATA: Record<string, TitleMeta> = {
  "iron-man": {
    imdb: "tt0371746",
    director: ["Jon Favreau"],
    runtime: 126,
    released: "2008-05-02",
  },
  "incredible-hulk": {
    imdb: "tt0800080",
    director: ["Louis Leterrier"],
    runtime: 112,
    released: "2008-06-13",
  },
  "iron-man-2": {
    imdb: "tt1228705",
    director: ["Jon Favreau"],
    runtime: 125,
    released: "2010-05-07",
  },
  thor: {
    imdb: "tt0800369",
    director: ["Kenneth Branagh"],
    runtime: 114,
    released: "2011-05-06",
  },
  "first-avenger": {
    imdb: "tt0458339",
    director: ["Joe Johnston"],
    runtime: 124,
    released: "2011-07-22",
  },
  avengers: {
    imdb: "tt0848228",
    director: ["Joss Whedon"],
    runtime: 142,
    released: "2012-05-04",
  },
  "iron-man-3": {
    imdb: "tt1300854",
    director: ["Shane Black"],
    runtime: 130,
    released: "2013-05-03",
  },
  "thor-dark-world": {
    imdb: "tt1981115",
    director: ["Alan Taylor"],
    runtime: 112,
    released: "2013-11-08",
  },
  "winter-soldier": {
    imdb: "tt1843866",
    director: ["Anthony Russo", "Joe Russo"],
    runtime: 136,
    released: "2014-04-04",
  },
  guardians: {
    imdb: "tt2015381",
    director: ["James Gunn"],
    runtime: 121,
    released: "2014-08-01",
  },
  "age-of-ultron": {
    imdb: "tt2395427",
    director: ["Joss Whedon"],
    runtime: 141,
    released: "2015-05-01",
  },
  "ant-man": {
    imdb: "tt0478970",
    director: ["Peyton Reed"],
    runtime: 117,
    released: "2015-07-17",
  },
  "civil-war": {
    imdb: "tt3498820",
    director: ["Anthony Russo", "Joe Russo"],
    runtime: 147,
    released: "2016-05-06",
  },
  "doctor-strange": {
    imdb: "tt1211837",
    director: ["Scott Derrickson"],
    runtime: 115,
    released: "2016-11-04",
  },
  "gotg-2": {
    imdb: "tt3896198",
    director: ["James Gunn"],
    runtime: 136,
    released: "2017-05-05",
  },
  homecoming: {
    imdb: "tt2250912",
    director: ["Jon Watts"],
    runtime: 133,
    released: "2017-07-07",
  },
  ragnarok: {
    imdb: "tt3501632",
    director: ["Taika Waititi"],
    runtime: 130,
    released: "2017-11-03",
  },
  "black-panther": {
    imdb: "tt1825683",
    director: ["Ryan Coogler"],
    runtime: 134,
    released: "2018-02-15",
  },
  "infinity-war": {
    imdb: "tt4154756",
    director: ["Anthony Russo", "Joe Russo"],
    runtime: 149,
    released: "2018-04-27",
  },
  "ant-man-wasp": {
    imdb: "tt5095030",
    director: ["Peyton Reed"],
    runtime: 118,
    released: "2018-07-06",
  },
  "captain-marvel": {
    imdb: "tt4154664",
    director: ["Ryan Fleck", "Anna Boden"],
    runtime: 124,
    released: "2019-03-08",
  },
  endgame: {
    imdb: "tt4154796",
    director: ["Anthony Russo", "Joe Russo"],
    runtime: 181,
    released: "2019-04-26",
  },
  "far-from-home": {
    imdb: "tt6320628",
    director: ["Jon Watts"],
    runtime: 129,
    released: "2019-07-02",
  },
  wandavision: { imdb: "tt9140560", creator: ["Jac Schaeffer"], episodes: 9 },
  "falcon-winter-soldier": {
    imdb: "tt9208876",
    creator: ["Malcolm Spellman"],
    episodes: 6,
  },
  "loki-s1": { imdb: "tt9140554", creator: ["Michael Waldron"] },
  "black-widow": {
    imdb: "tt3480822",
    director: ["Cate Shortland"],
    runtime: 133,
    released: "2021-07-09",
  },
  "what-if-s1": { imdb: "tt10168312" },
  "shang-chi": {
    imdb: "tt9376612",
    director: ["Destin Daniel Cretton"],
    runtime: 132,
    released: "2021-09-03",
  },
  eternals: {
    imdb: "tt9032400",
    director: ["Chloé Zhao"],
    runtime: 156,
    released: "2021-11-05",
  },
  hawkeye: { imdb: "tt10160804", creator: ["Jonathan Igla"], episodes: 6 },
  "no-way-home": {
    imdb: "tt10872600",
    director: ["Jon Watts"],
    runtime: 148,
    released: "2021-12-17",
  },
  "moon-knight": {
    imdb: "tt10234724",
    creator: ["Jeremy Slater"],
    episodes: 6,
  },
  "multiverse-of-madness": {
    imdb: "tt9419884",
    director: ["Sam Raimi"],
    runtime: 126,
    released: "2022-05-06",
  },
  "ms-marvel": { imdb: "tt10857164", creator: ["Bisha K. Ali"], episodes: 6 },
  "love-and-thunder": {
    imdb: "tt10648342",
    director: ["Taika Waititi"],
    runtime: 119,
    released: "2022-07-08",
  },
  "she-hulk": { imdb: "tt10857160", creator: ["Jessica Gao"], episodes: 9 },
  "werewolf-by-night": {
    imdb: "tt15318872",
    creator: ["Michael Giacchino"],
    episodes: 1,
    released: "2022-10-07",
  },
  "wakanda-forever": {
    imdb: "tt9114286",
    director: ["Ryan Coogler"],
    runtime: 161,
    released: "2022-11-11",
  },
  "gotg-holiday": {
    imdb: "tt13623136",
    creator: ["James Gunn"],
    episodes: 1,
    released: "2022-11-25",
  },
  quantumania: {
    imdb: "tt10954600",
    director: ["Peyton Reed"],
    runtime: 125,
    released: "2023-02-17",
  },
  "gotg-3": {
    imdb: "tt6791350",
    director: ["James Gunn"],
    runtime: 150,
    released: "2023-05-05",
  },
  "secret-invasion": {
    imdb: "tt13157618",
    creator: ["Kyle Bradstreet"],
    episodes: 6,
  },
  "loki-s2": { imdb: "tt9140554", creator: ["Michael Waldron"] },
  "the-marvels": {
    imdb: "tt10676048",
    director: ["Nia DaCosta"],
    runtime: 105,
    released: "2023-11-10",
  },
  "what-if-s2": { imdb: "tt10168312" },
  echo: { imdb: "tt13966962", episodes: 5 },
  "deadpool-wolverine": {
    imdb: "tt6263850",
    director: ["Shawn Levy"],
    runtime: 128,
    released: "2024-07-26",
  },
  "agatha-all-along": {
    imdb: "tt15571732",
    creator: ["Jac Schaeffer"],
    episodes: 9,
  },
  "what-if-s3": { imdb: "tt10168312" },
  "your-friendly-neighborhood-spider-man": {
    imdb: "tt16027074",
    episodes: 10,
    released: "2025-01-29",
  },
  "brave-new-world": {
    imdb: "tt14513804",
    director: ["Julius Onah"],
    runtime: 118,
    released: "2025-02-14",
  },
  "daredevil-born-again": { imdb: "tt18923754" },
  thunderbolts: {
    imdb: "tt20969586",
    director: ["Jake Schreier"],
    runtime: 126,
    released: "2025-05-02",
  },
  ironheart: { imdb: "tt13623126", creator: ["Chinaka Hodge"], episodes: 6 },
  "fantastic-four-first-steps": {
    imdb: "tt10676052",
    director: ["Matt Shakman"],
    runtime: 114,
    released: "2025-07-25",
  },
  "eyes-of-wakanda": {
    imdb: "tt13968252",
    creator: ["Ryan Coogler"],
    episodes: 4,
  },
  "marvel-zombies": {
    imdb: "tt16027014",
    creator: ["Bryan Andrews"],
    episodes: 4,
  },
  "wonder-man": {
    imdb: "tt21066182",
    creator: ["Destin Daniel Cretton", "Andrew Guest"],
    episodes: 8,
  },
  "born-again-s2": { imdb: "tt18923754" },
  "punisher-one-last-kill": {
    imdb: "tt36042156",
    creator: ["Reinaldo Marcus Green"],
    released: "2026-05-12",
  },
  "brand-new-day": {
    imdb: "tt22084616",
    director: ["Destin Daniel Cretton"],
    runtime: 145,
    released: "2026-07-31",
  },
  visionquest: {
    imdb: "tt23112594",
    creator: ["Terry Matalas", "Christopher J. Byrne", "Vincenzo Natali"],
    episodes: 8,
  },
  "avengers-doomsday": {
    imdb: "tt21357150",
    director: ["Joe Russo", "Anthony Russo"],
    released: "2026-12-18",
  },
  "born-again-s3": { imdb: "tt18923754" },
  "avengers-secret-wars": {
    imdb: "tt21361444",
    director: ["Anthony Russo", "Joe Russo"],
    released: "2027-12-17",
  },
  "x-men": {
    imdb: "tt0120903",
    director: ["Bryan Singer"],
    runtime: 104,
    released: "2000-11-21",
  },
  x2: {
    imdb: "tt0290334",
    director: ["Bryan Singer"],
    runtime: 134,
    released: "2003-05-02",
  },
  "last-stand": {
    imdb: "tt0376994",
    director: ["Brett Ratner"],
    runtime: 104,
    released: "2006-05-26",
  },
  "origins-wolverine": {
    imdb: "tt0458525",
    director: ["Gavin Hood"],
    runtime: 107,
    released: "2009-05-01",
  },
  "the-wolverine": {
    imdb: "tt1430132",
    director: ["James Mangold"],
    runtime: 138,
    released: "2013-07-26",
  },
  "first-class": {
    imdb: "tt1270798",
    director: ["Matthew Vaughn"],
    runtime: 131,
    released: "2011-06-03",
  },
  "days-of-future-past": {
    imdb: "tt1877832",
    director: ["Bryan Singer"],
    runtime: 131,
    released: "2014-05-23",
  },
  apocalypse: {
    imdb: "tt3385516",
    director: ["Bryan Singer"],
    runtime: 131,
    released: "2016-05-27",
  },
  "dark-phoenix": {
    imdb: "tt6565702",
    director: ["Simon Kinberg"],
    runtime: 114,
    released: "2019-06-07",
  },
  "new-mutants": {
    imdb: "tt4682266",
    director: ["Josh Boone"],
    runtime: 94,
    released: "2020-08-28",
  },
  logan: {
    imdb: "tt3315342",
    director: ["James Mangold"],
    runtime: 137,
    released: "2017-03-03",
  },
  deadpool: {
    imdb: "tt1431045",
    director: ["Tim Miller"],
    runtime: 108,
    released: "2016-02-12",
  },
  "deadpool-2": {
    imdb: "tt5463162",
    director: ["David Leitch"],
    runtime: 119,
    released: "2018-05-18",
  },
  "fantastic-four-2005": {
    imdb: "tt0120667",
    director: ["Tim Story"],
    runtime: 102,
    released: "2005-07-08",
  },
  "rise-silver-surfer": {
    imdb: "tt0486576",
    director: ["Tim Story"],
    runtime: 92,
    released: "2007-06-15",
  },
  fant4stic: {
    imdb: "tt1502712",
    director: ["Josh Trank"],
    runtime: 100,
    released: "2015-08-07",
  },
  "daredevil-2003": {
    imdb: "tt0287978",
    director: ["Mark Steven Johnson"],
    runtime: 103,
    released: "2003-02-14",
  },
  "elektra-2005": {
    imdb: "tt0357277",
    director: ["Rob Bowman"],
    runtime: 96,
    released: "2005-01-14",
  },
  "spider-man-2002": {
    imdb: "tt0145487",
    director: ["Sam Raimi"],
    runtime: 121,
    released: "2002-05-03",
  },
  "spider-man-2": {
    imdb: "tt0316654",
    director: ["Sam Raimi"],
    runtime: 122,
    released: "2004-06-30",
  },
  "spider-man-3": {
    imdb: "tt0413300",
    director: ["Sam Raimi"],
    runtime: 139,
    released: "2007-05-04",
  },
  "amazing-spider-man": {
    imdb: "tt0948470",
    director: ["Marc Webb"],
    runtime: 136,
    released: "2012-07-03",
  },
  "amazing-spider-man-2": {
    imdb: "tt1872181",
    director: ["Marc Webb"],
    runtime: 142,
    released: "2014-05-02",
  },
  venom: {
    imdb: "tt1270797",
    director: ["Ruben Fleischer"],
    runtime: 112,
    released: "2018-10-04",
  },
  "venom-carnage": {
    imdb: "tt7097896",
    director: ["Andy Serkis"],
    runtime: 97,
    released: "2021-10-01",
  },
  morbius: {
    imdb: "tt5108870",
    director: ["Daniel Espinosa"],
    runtime: 104,
    released: "2022-04-01",
  },
  "madame-web": {
    imdb: "tt11057302",
    director: ["S. J. Clarkson"],
    runtime: 116,
    released: "2024-02-14",
  },
  "venom-last-dance": {
    imdb: "tt16366836",
    director: ["Kelly Marcel"],
    runtime: 109,
    released: "2024-10-25",
  },
  kraven: {
    imdb: "tt8790086",
    director: ["J. C. Chandor"],
    runtime: 127,
    released: "2024-12-13",
  },
  "into-spider-verse": {
    imdb: "tt4633694",
    director: ["Peter Ramsey", "Rodney Rothman", "Bob Persichetti"],
    runtime: 116,
    released: "2018-12-14",
  },
  "across-spider-verse": {
    imdb: "tt9362722",
    director: ["Joaquim Dos Santos", "Kemp Powers", "Justin K. Thompson"],
    runtime: 140,
    released: "2023-06-01",
  },
};

export const meta = (id: string): TitleMeta => METADATA[id] ?? {};
