/**
 * Poster artwork per title id. Generated by \`pnpm posters:optimize\`; do not
 * hand-edit — sources live in assets/posters-src/ and never ship.
 *
 *  - \`fit: "cover"\` is a real 2:3 poster and fills the card.
 *  - \`fit: "contain"\` is landscape key art (Wikipedia has no free poster for
 *    most series) and is centred inside the card rather than cropped to death.
 *  - \`cell\` is where the title sits on the sprite atlas — the zoomed-out map
 *    paints every card from that ONE image, and only fetches \`src\` once a card
 *    is drawn bigger than its cell.
 *
 * Filenames carry a content hash, so they are served immutable for a year.
 * Anything missing falls back to a typographic card in its reality's colour.
 */
export type PosterCell = { x: number; y: number; w: number; h: number };
export type PosterEntry = {
  src: string;
  fit: "cover" | "contain";
  cell: PosterCell;
};

/** The sprite sheet every thumbnail on the map comes from: one request, total. */
export const POSTER_ATLAS = {
  src: "/posters/atlas.b0eed064.webp",
  width: 1200,
  height: 1752,
};

export const POSTERS: Record<string, PosterEntry> = {
  "across-spider-verse": {
    src: "/posters/across-spider-verse.7b91f0d3.webp",
    fit: "cover",
    cell: { x: 0, y: 0, w: 96, h: 142 },
  },
  "age-of-ultron": {
    src: "/posters/age-of-ultron.bfe64571.webp",
    fit: "cover",
    cell: { x: 96, y: 0, w: 96, h: 142 },
  },
  "amazing-spider-man-2": {
    src: "/posters/amazing-spider-man-2.63f61fe0.webp",
    fit: "cover",
    cell: { x: 192, y: 0, w: 96, h: 142 },
  },
  "amazing-spider-man": {
    src: "/posters/amazing-spider-man.8eec5a9b.webp",
    fit: "cover",
    cell: { x: 288, y: 0, w: 96, h: 142 },
  },
  "ant-man-wasp": {
    src: "/posters/ant-man-wasp.91ef6f20.webp",
    fit: "cover",
    cell: { x: 384, y: 0, w: 96, h: 142 },
  },
  "ant-man": {
    src: "/posters/ant-man.329343dd.webp",
    fit: "cover",
    cell: { x: 480, y: 0, w: 96, h: 142 },
  },
  apocalypse: {
    src: "/posters/apocalypse.25308fad.webp",
    fit: "cover",
    cell: { x: 576, y: 0, w: 96, h: 142 },
  },
  "avengers-doomsday": {
    src: "/posters/avengers-doomsday.5881dc11.webp",
    fit: "cover",
    cell: { x: 672, y: 0, w: 96, h: 142 },
  },
  avengers: {
    src: "/posters/avengers.9b8bdc9d.webp",
    fit: "cover",
    cell: { x: 768, y: 0, w: 96, h: 142 },
  },
  "black-panther": {
    src: "/posters/black-panther.9a1f78ab.webp",
    fit: "cover",
    cell: { x: 864, y: 0, w: 96, h: 142 },
  },
  "black-widow": {
    src: "/posters/black-widow.6ad88976.webp",
    fit: "cover",
    cell: { x: 960, y: 0, w: 96, h: 142 },
  },
  "born-again-s2": {
    src: "/posters/born-again-s2.8c51a837.webp",
    fit: "cover",
    cell: { x: 1056, y: 0, w: 96, h: 142 },
  },
  "brand-new-day": {
    src: "/posters/brand-new-day.283c60ac.webp",
    fit: "cover",
    cell: { x: 0, y: 142, w: 96, h: 142 },
  },
  "brave-new-world": {
    src: "/posters/brave-new-world.db8daa43.webp",
    fit: "cover",
    cell: { x: 96, y: 142, w: 96, h: 142 },
  },
  "captain-marvel": {
    src: "/posters/captain-marvel.6e4d5309.webp",
    fit: "cover",
    cell: { x: 192, y: 142, w: 96, h: 142 },
  },
  "civil-war": {
    src: "/posters/civil-war.6cd7d89b.webp",
    fit: "cover",
    cell: { x: 288, y: 142, w: 96, h: 142 },
  },
  "daredevil-2003": {
    src: "/posters/daredevil-2003.47b92879.webp",
    fit: "cover",
    cell: { x: 384, y: 142, w: 96, h: 142 },
  },
  "dark-phoenix": {
    src: "/posters/dark-phoenix.84211d34.webp",
    fit: "cover",
    cell: { x: 480, y: 142, w: 96, h: 142 },
  },
  "days-of-future-past": {
    src: "/posters/days-of-future-past.8ea30188.webp",
    fit: "cover",
    cell: { x: 576, y: 142, w: 96, h: 142 },
  },
  "deadpool-2": {
    src: "/posters/deadpool-2.b96935ec.webp",
    fit: "cover",
    cell: { x: 672, y: 142, w: 96, h: 142 },
  },
  "deadpool-wolverine": {
    src: "/posters/deadpool-wolverine.d8c785a7.webp",
    fit: "cover",
    cell: { x: 768, y: 142, w: 96, h: 142 },
  },
  deadpool: {
    src: "/posters/deadpool.53ded837.webp",
    fit: "cover",
    cell: { x: 864, y: 142, w: 96, h: 142 },
  },
  "doctor-strange": {
    src: "/posters/doctor-strange.c401c76b.webp",
    fit: "cover",
    cell: { x: 960, y: 142, w: 96, h: 142 },
  },
  "elektra-2005": {
    src: "/posters/elektra-2005.ea844f01.webp",
    fit: "cover",
    cell: { x: 1056, y: 142, w: 96, h: 142 },
  },
  endgame: {
    src: "/posters/endgame.90815412.webp",
    fit: "cover",
    cell: { x: 0, y: 284, w: 96, h: 142 },
  },
  eternals: {
    src: "/posters/eternals.e4e07bf2.webp",
    fit: "cover",
    cell: { x: 96, y: 284, w: 96, h: 142 },
  },
  fant4stic: {
    src: "/posters/fant4stic.6e3c966f.webp",
    fit: "cover",
    cell: { x: 192, y: 284, w: 96, h: 142 },
  },
  "fantastic-four-2005": {
    src: "/posters/fantastic-four-2005.1ff9a40b.webp",
    fit: "cover",
    cell: { x: 288, y: 284, w: 96, h: 142 },
  },
  "fantastic-four-first-steps": {
    src: "/posters/fantastic-four-first-steps.1c160c8c.webp",
    fit: "cover",
    cell: { x: 384, y: 284, w: 96, h: 142 },
  },
  "far-from-home": {
    src: "/posters/far-from-home.3a978e41.webp",
    fit: "cover",
    cell: { x: 480, y: 284, w: 96, h: 142 },
  },
  "first-avenger": {
    src: "/posters/first-avenger.ebe6aa1e.webp",
    fit: "cover",
    cell: { x: 576, y: 284, w: 96, h: 142 },
  },
  "first-class": {
    src: "/posters/first-class.39ba584e.webp",
    fit: "cover",
    cell: { x: 672, y: 284, w: 96, h: 142 },
  },
  "gotg-2": {
    src: "/posters/gotg-2.22e2d19c.webp",
    fit: "cover",
    cell: { x: 768, y: 284, w: 96, h: 142 },
  },
  "gotg-3": {
    src: "/posters/gotg-3.2c6df434.webp",
    fit: "cover",
    cell: { x: 864, y: 284, w: 96, h: 142 },
  },
  "gotg-holiday": {
    src: "/posters/gotg-holiday.dd5e5831.webp",
    fit: "cover",
    cell: { x: 960, y: 284, w: 96, h: 142 },
  },
  guardians: {
    src: "/posters/guardians.3eaeaa6d.webp",
    fit: "cover",
    cell: { x: 1056, y: 284, w: 96, h: 142 },
  },
  homecoming: {
    src: "/posters/homecoming.4477e4ca.webp",
    fit: "cover",
    cell: { x: 0, y: 426, w: 96, h: 142 },
  },
  "incredible-hulk": {
    src: "/posters/incredible-hulk.823a9f4d.webp",
    fit: "cover",
    cell: { x: 96, y: 426, w: 96, h: 142 },
  },
  "infinity-war": {
    src: "/posters/infinity-war.96ca7abe.webp",
    fit: "cover",
    cell: { x: 192, y: 426, w: 96, h: 142 },
  },
  "into-spider-verse": {
    src: "/posters/into-spider-verse.9695ca5c.webp",
    fit: "cover",
    cell: { x: 288, y: 426, w: 96, h: 142 },
  },
  "iron-man-2": {
    src: "/posters/iron-man-2.0640be55.webp",
    fit: "cover",
    cell: { x: 384, y: 426, w: 96, h: 142 },
  },
  "iron-man-3": {
    src: "/posters/iron-man-3.3137f5fb.webp",
    fit: "cover",
    cell: { x: 480, y: 426, w: 96, h: 142 },
  },
  "iron-man": {
    src: "/posters/iron-man.d92d5bd1.webp",
    fit: "cover",
    cell: { x: 576, y: 426, w: 96, h: 142 },
  },
  kraven: {
    src: "/posters/kraven.912fe154.webp",
    fit: "cover",
    cell: { x: 672, y: 426, w: 96, h: 142 },
  },
  "last-stand": {
    src: "/posters/last-stand.2598a4f7.webp",
    fit: "cover",
    cell: { x: 768, y: 426, w: 96, h: 142 },
  },
  logan: {
    src: "/posters/logan.079d39dc.webp",
    fit: "cover",
    cell: { x: 864, y: 426, w: 96, h: 142 },
  },
  "love-and-thunder": {
    src: "/posters/love-and-thunder.c21cef76.webp",
    fit: "cover",
    cell: { x: 960, y: 426, w: 96, h: 142 },
  },
  "madame-web": {
    src: "/posters/madame-web.923f40a7.webp",
    fit: "cover",
    cell: { x: 1056, y: 426, w: 96, h: 142 },
  },
  morbius: {
    src: "/posters/morbius.d49aff3f.webp",
    fit: "cover",
    cell: { x: 0, y: 568, w: 96, h: 142 },
  },
  "multiverse-of-madness": {
    src: "/posters/multiverse-of-madness.1bba5fc0.webp",
    fit: "cover",
    cell: { x: 96, y: 568, w: 96, h: 142 },
  },
  "new-mutants": {
    src: "/posters/new-mutants.1dafeb56.webp",
    fit: "cover",
    cell: { x: 192, y: 568, w: 96, h: 142 },
  },
  "no-way-home": {
    src: "/posters/no-way-home.2efc4b9a.webp",
    fit: "cover",
    cell: { x: 288, y: 568, w: 96, h: 142 },
  },
  "origins-wolverine": {
    src: "/posters/origins-wolverine.9a8da771.webp",
    fit: "cover",
    cell: { x: 384, y: 568, w: 96, h: 142 },
  },
  "punisher-one-last-kill": {
    src: "/posters/punisher-one-last-kill.cd9c0c3d.webp",
    fit: "cover",
    cell: { x: 480, y: 568, w: 96, h: 142 },
  },
  quantumania: {
    src: "/posters/quantumania.dc50bfdb.webp",
    fit: "cover",
    cell: { x: 576, y: 568, w: 96, h: 142 },
  },
  ragnarok: {
    src: "/posters/ragnarok.1a0d06c2.webp",
    fit: "cover",
    cell: { x: 672, y: 568, w: 96, h: 142 },
  },
  "rise-silver-surfer": {
    src: "/posters/rise-silver-surfer.226615a1.webp",
    fit: "cover",
    cell: { x: 768, y: 568, w: 96, h: 142 },
  },
  "shang-chi": {
    src: "/posters/shang-chi.ca34451b.webp",
    fit: "cover",
    cell: { x: 864, y: 568, w: 96, h: 142 },
  },
  "spider-man-2": {
    src: "/posters/spider-man-2.b56ca18e.webp",
    fit: "cover",
    cell: { x: 960, y: 568, w: 96, h: 142 },
  },
  "spider-man-2002": {
    src: "/posters/spider-man-2002.bebb66bb.webp",
    fit: "cover",
    cell: { x: 1056, y: 568, w: 96, h: 142 },
  },
  "spider-man-3": {
    src: "/posters/spider-man-3.424b2556.webp",
    fit: "cover",
    cell: { x: 0, y: 710, w: 96, h: 142 },
  },
  "the-marvels": {
    src: "/posters/the-marvels.346c212f.webp",
    fit: "cover",
    cell: { x: 96, y: 710, w: 96, h: 142 },
  },
  "the-wolverine": {
    src: "/posters/the-wolverine.c094d055.webp",
    fit: "cover",
    cell: { x: 192, y: 710, w: 96, h: 142 },
  },
  "thor-dark-world": {
    src: "/posters/thor-dark-world.1cf05f71.webp",
    fit: "cover",
    cell: { x: 288, y: 710, w: 96, h: 142 },
  },
  thor: {
    src: "/posters/thor.e3a02e5e.webp",
    fit: "cover",
    cell: { x: 384, y: 710, w: 96, h: 142 },
  },
  thunderbolts: {
    src: "/posters/thunderbolts.f56e41ab.webp",
    fit: "cover",
    cell: { x: 480, y: 710, w: 96, h: 142 },
  },
  "venom-carnage": {
    src: "/posters/venom-carnage.dfceed83.webp",
    fit: "cover",
    cell: { x: 576, y: 710, w: 96, h: 142 },
  },
  "venom-last-dance": {
    src: "/posters/venom-last-dance.736ebbd2.webp",
    fit: "cover",
    cell: { x: 672, y: 710, w: 96, h: 142 },
  },
  venom: {
    src: "/posters/venom.4f8676c1.webp",
    fit: "cover",
    cell: { x: 768, y: 710, w: 96, h: 142 },
  },
  "wakanda-forever": {
    src: "/posters/wakanda-forever.f564b093.webp",
    fit: "cover",
    cell: { x: 864, y: 710, w: 96, h: 142 },
  },
  "werewolf-by-night": {
    src: "/posters/werewolf-by-night.8e8f4d62.webp",
    fit: "cover",
    cell: { x: 960, y: 710, w: 96, h: 142 },
  },
  "what-if-s2": {
    src: "/posters/what-if-s2.2d464d2d.webp",
    fit: "cover",
    cell: { x: 1056, y: 710, w: 96, h: 142 },
  },
  "what-if-s3": {
    src: "/posters/what-if-s3.a90d9092.webp",
    fit: "cover",
    cell: { x: 0, y: 852, w: 96, h: 142 },
  },
  "winter-soldier": {
    src: "/posters/winter-soldier.f9af3243.webp",
    fit: "cover",
    cell: { x: 96, y: 852, w: 96, h: 142 },
  },
  "x-men": {
    src: "/posters/x-men.f6841a91.webp",
    fit: "cover",
    cell: { x: 192, y: 852, w: 96, h: 142 },
  },
  x2: {
    src: "/posters/x2.73653e69.webp",
    fit: "cover",
    cell: { x: 288, y: 852, w: 96, h: 142 },
  },
  "punisher-1989": {
    src: "/posters/punisher-1989.b8ce9f54.webp",
    fit: "cover",
    cell: { x: 384, y: 852, w: 96, h: 142 },
  },
  blade: {
    src: "/posters/blade.0f1aaa9d.webp",
    fit: "cover",
    cell: { x: 480, y: 852, w: 96, h: 142 },
  },
  "blade-2": {
    src: "/posters/blade-2.9b18861f.webp",
    fit: "cover",
    cell: { x: 576, y: 852, w: 96, h: 142 },
  },
  "blade-trinity": {
    src: "/posters/blade-trinity.62fceaa2.webp",
    fit: "cover",
    cell: { x: 672, y: 852, w: 96, h: 142 },
  },
  "hulk-2003": {
    src: "/posters/hulk-2003.84368dd9.webp",
    fit: "cover",
    cell: { x: 768, y: 852, w: 96, h: 142 },
  },
  "punisher-2004": {
    src: "/posters/punisher-2004.2e27f382.webp",
    fit: "cover",
    cell: { x: 864, y: 852, w: 96, h: 142 },
  },
  "punisher-war-zone": {
    src: "/posters/punisher-war-zone.16c06164.webp",
    fit: "cover",
    cell: { x: 960, y: 852, w: 96, h: 142 },
  },
  "ghost-rider-2007": {
    src: "/posters/ghost-rider-2007.78d7f88a.webp",
    fit: "cover",
    cell: { x: 1056, y: 852, w: 96, h: 142 },
  },
  "spirit-of-vengeance": {
    src: "/posters/spirit-of-vengeance.408cb770.webp",
    fit: "cover",
    cell: { x: 0, y: 994, w: 96, h: 142 },
  },
  "agatha-all-along": {
    src: "/posters/agatha-all-along.b588a290.webp",
    fit: "contain",
    cell: { x: 0, y: 1136, w: 156, h: 88 },
  },
  "avengers-secret-wars": {
    src: "/posters/avengers-secret-wars.1e325af5.webp",
    fit: "contain",
    cell: { x: 156, y: 1136, w: 156, h: 88 },
  },
  "daredevil-born-again": {
    src: "/posters/daredevil-born-again.b0be50f4.webp",
    fit: "contain",
    cell: { x: 312, y: 1136, w: 156, h: 88 },
  },
  echo: {
    src: "/posters/echo.dc2eff16.webp",
    fit: "contain",
    cell: { x: 468, y: 1136, w: 156, h: 88 },
  },
  "eyes-of-wakanda": {
    src: "/posters/eyes-of-wakanda.f9bade7e.webp",
    fit: "contain",
    cell: { x: 624, y: 1136, w: 156, h: 88 },
  },
  "falcon-winter-soldier": {
    src: "/posters/falcon-winter-soldier.1fdeabd1.webp",
    fit: "contain",
    cell: { x: 780, y: 1136, w: 156, h: 88 },
  },
  hawkeye: {
    src: "/posters/hawkeye.50712f46.webp",
    fit: "contain",
    cell: { x: 936, y: 1136, w: 156, h: 88 },
  },
  ironheart: {
    src: "/posters/ironheart.f645fb61.webp",
    fit: "contain",
    cell: { x: 0, y: 1224, w: 156, h: 88 },
  },
  "loki-s1": {
    src: "/posters/loki-s1.642aa9f7.webp",
    fit: "contain",
    cell: { x: 156, y: 1224, w: 156, h: 88 },
  },
  "loki-s2": {
    src: "/posters/loki-s2.642aa9f7.webp",
    fit: "contain",
    cell: { x: 312, y: 1224, w: 156, h: 88 },
  },
  "marvel-zombies": {
    src: "/posters/marvel-zombies.d8f43b55.webp",
    fit: "contain",
    cell: { x: 468, y: 1224, w: 156, h: 88 },
  },
  "moon-knight": {
    src: "/posters/moon-knight.363baeda.webp",
    fit: "contain",
    cell: { x: 624, y: 1224, w: 156, h: 88 },
  },
  "ms-marvel": {
    src: "/posters/ms-marvel.89a89cf5.webp",
    fit: "contain",
    cell: { x: 780, y: 1224, w: 156, h: 88 },
  },
  "secret-invasion": {
    src: "/posters/secret-invasion.95f6d449.webp",
    fit: "contain",
    cell: { x: 936, y: 1224, w: 156, h: 88 },
  },
  "she-hulk": {
    src: "/posters/she-hulk.be9161b3.webp",
    fit: "contain",
    cell: { x: 0, y: 1312, w: 156, h: 88 },
  },
  visionquest: {
    src: "/posters/visionquest.579553ff.webp",
    fit: "contain",
    cell: { x: 156, y: 1312, w: 156, h: 88 },
  },
  wandavision: {
    src: "/posters/wandavision.aea940a5.webp",
    fit: "contain",
    cell: { x: 312, y: 1312, w: 156, h: 88 },
  },
  "what-if-s1": {
    src: "/posters/what-if-s1.4580ec0e.webp",
    fit: "contain",
    cell: { x: 468, y: 1312, w: 156, h: 88 },
  },
  "your-friendly-neighborhood-spider-man": {
    src: "/posters/your-friendly-neighborhood-spider-man.cc3178ae.webp",
    fit: "contain",
    cell: { x: 624, y: 1312, w: 156, h: 88 },
  },
  "agents-of-shield-s1": {
    src: "/posters/agents-of-shield-s1.05a52f1f.webp",
    fit: "contain",
    cell: { x: 780, y: 1312, w: 156, h: 88 },
  },
  "agents-of-shield-s2": {
    src: "/posters/agents-of-shield-s2.05a52f1f.webp",
    fit: "contain",
    cell: { x: 936, y: 1312, w: 156, h: 88 },
  },
  "agent-carter-s1": {
    src: "/posters/agent-carter-s1.4267b165.webp",
    fit: "contain",
    cell: { x: 0, y: 1400, w: 156, h: 88 },
  },
  "agents-of-shield-s3": {
    src: "/posters/agents-of-shield-s3.05a52f1f.webp",
    fit: "contain",
    cell: { x: 156, y: 1400, w: 156, h: 88 },
  },
  "agent-carter-s2": {
    src: "/posters/agent-carter-s2.4267b165.webp",
    fit: "contain",
    cell: { x: 312, y: 1400, w: 156, h: 88 },
  },
  "agents-of-shield-s4": {
    src: "/posters/agents-of-shield-s4.05a52f1f.webp",
    fit: "contain",
    cell: { x: 468, y: 1400, w: 156, h: 88 },
  },
  "agents-of-shield-s5": {
    src: "/posters/agents-of-shield-s5.05a52f1f.webp",
    fit: "contain",
    cell: { x: 624, y: 1400, w: 156, h: 88 },
  },
  inhumans: {
    src: "/posters/inhumans.a78cde26.webp",
    fit: "contain",
    cell: { x: 780, y: 1400, w: 156, h: 88 },
  },
  "agents-of-shield-s6": {
    src: "/posters/agents-of-shield-s6.05a52f1f.webp",
    fit: "contain",
    cell: { x: 936, y: 1400, w: 156, h: 88 },
  },
  "agents-of-shield-s7": {
    src: "/posters/agents-of-shield-s7.05a52f1f.webp",
    fit: "contain",
    cell: { x: 0, y: 1488, w: 156, h: 88 },
  },
  "runaways-s1": {
    src: "/posters/runaways-s1.edc6046c.webp",
    fit: "contain",
    cell: { x: 156, y: 1488, w: 156, h: 88 },
  },
  "cloak-dagger-s1": {
    src: "/posters/cloak-dagger-s1.3909da0e.webp",
    fit: "contain",
    cell: { x: 312, y: 1488, w: 156, h: 88 },
  },
  "runaways-s2": {
    src: "/posters/runaways-s2.edc6046c.webp",
    fit: "contain",
    cell: { x: 468, y: 1488, w: 156, h: 88 },
  },
  "cloak-dagger-s2": {
    src: "/posters/cloak-dagger-s2.3909da0e.webp",
    fit: "contain",
    cell: { x: 624, y: 1488, w: 156, h: 88 },
  },
  "runaways-s3": {
    src: "/posters/runaways-s3.edc6046c.webp",
    fit: "contain",
    cell: { x: 780, y: 1488, w: 156, h: 88 },
  },
  "jessica-jones-s1": {
    src: "/posters/jessica-jones-s1.441c57de.webp",
    fit: "contain",
    cell: { x: 936, y: 1488, w: 156, h: 88 },
  },
  "luke-cage-s1": {
    src: "/posters/luke-cage-s1.d65e1f30.webp",
    fit: "contain",
    cell: { x: 0, y: 1576, w: 156, h: 88 },
  },
  "iron-fist-s1": {
    src: "/posters/iron-fist-s1.a5d8439d.webp",
    fit: "contain",
    cell: { x: 156, y: 1576, w: 156, h: 88 },
  },
  defenders: {
    src: "/posters/defenders.1aac0b68.webp",
    fit: "contain",
    cell: { x: 312, y: 1576, w: 156, h: 88 },
  },
  "punisher-nf-s1": {
    src: "/posters/punisher-nf-s1.495eb179.webp",
    fit: "contain",
    cell: { x: 468, y: 1576, w: 156, h: 88 },
  },
  "jessica-jones-s2": {
    src: "/posters/jessica-jones-s2.441c57de.webp",
    fit: "contain",
    cell: { x: 624, y: 1576, w: 156, h: 88 },
  },
  "luke-cage-s2": {
    src: "/posters/luke-cage-s2.d65e1f30.webp",
    fit: "contain",
    cell: { x: 780, y: 1576, w: 156, h: 88 },
  },
  "iron-fist-s2": {
    src: "/posters/iron-fist-s2.a5d8439d.webp",
    fit: "contain",
    cell: { x: 936, y: 1576, w: 156, h: 88 },
  },
  "punisher-nf-s2": {
    src: "/posters/punisher-nf-s2.495eb179.webp",
    fit: "contain",
    cell: { x: 0, y: 1664, w: 156, h: 88 },
  },
  "jessica-jones-s3": {
    src: "/posters/jessica-jones-s3.441c57de.webp",
    fit: "contain",
    cell: { x: 156, y: 1664, w: 156, h: 88 },
  },
  "daredevil-nf-s1": {
    src: "/posters/daredevil-nf-s1.5ee4533b.webp",
    fit: "contain",
    cell: { x: 312, y: 1664, w: 156, h: 88 },
  },
  "daredevil-nf-s2": {
    src: "/posters/daredevil-nf-s2.5ee4533b.webp",
    fit: "contain",
    cell: { x: 468, y: 1664, w: 156, h: 88 },
  },
  "daredevil-nf-s3": {
    src: "/posters/daredevil-nf-s3.5ee4533b.webp",
    fit: "contain",
    cell: { x: 624, y: 1664, w: 156, h: 88 },
  },
};

export const poster = (id: string): PosterEntry | null => POSTERS[id] ?? null;
